name: Test Microk8s
on:
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Install MicroK8s
    steps:
    - uses: balchua/microk8s-actions@v0.1.3
      with:
        channel: 'latest/stable'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test nginx
      id: microk8snginx
      run: |
        kubectl get no -o wide
        kubectl get pods -A -o wide
        kubectl apply -f ${{ github.workspace }}/deploy/nginx.yaml
        kubectl expose deployment nginx-deployment --name nginx-srv2 --cluster-ip=10.152.183.210
        kubectl rollout status deployment/nginx-deployment
        curl 10.152.183.210 | grep nginx
